# workflow for QA tests

name: CI for push in all branches

# Controls when the workflow will run
on:
# Workflow will run when pushed to any branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with: 
        repository: zengzihui/DevOps_Oct2021_Team04
    - name: Checkout Test Script
      uses: actions/checkout@v2
      with:
        repository: rlry72/DevOpsQA_Team4
        path: tests
        token: ${{ secrets.QA_REPO }}
    - name: Linter Check with Flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Begin Pytest
      run: |
        mv ./tests/*.* ./
        pytest --cov -v --junitxml=report.xml