# Workflow for approving pull requests
name: Approve_Pull_Requests

# Control
on:
  # Trigger
  pull_request_review:
     types: [submitted]

permissions:
  pull-requests: write

jobs:
  # label pull request as "Dev Team Approved"
  label_pr:
    # type of runner that the job will run on
      runs-on: ubuntu-latest
      
      # Task to run
      steps:
  
            
        # labelling pull-request with 'Dev Team Approved' once tech lead approves of code review.
        - name: Add label to pull request
          if: ${{ github.event.review.state == 'approved' }}
          
        # labelling issue with 'Dev Team Approved' once tech lead approves of code review.
          uses: buildsville/add-remove-label@v1
          with:
            token: ${{secrets.GITHUB_TOKEN}}
            label: Dev Team Approved
            type: add
            
        - name: Remove label to pull request
          if: ${{ github.event.review.state != 'approved' }}
          
        # remove labelling when not approved
          uses: buildsville/add-remove-label@v1
          with:
            token: ${{secrets.GITHUB_TOKEN}}
            label: Dev Team Approved
            type: remove
        
        # ping QA Lead for testing when code review is approved
        - name: ping QA Lead for testing
        if: ${{ github.event.review.state == 'approved' }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: '@rlry72 User story in this pull request is ready for testing'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        # Send notification to group discord to notify QA lead for testing
        - name: Discord notification
        if: ${{ github.event.review.state == 'approved' }}
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/918820417467199498/9bnSpC3afr6euVolvsCDuNXwM6hUcElqeN5Vl2LDUObNbXEEhWiYV1tlddCHURgHBphV
        uses: Ilshidur/action-discord@master
        with:
          args: 'QA Lead, user story in pull request ${{ github.event.pull_request.html_url }} is ready to be reviewed and tested.