name: Notify TechLead On Issue In Review

on:
  project_card:
    types:
      - moved

jobs:
  notify-tech-lead:
    if: github.event.project_card.column_id == '17160041'
    runs-on: ubuntu-latest
    steps:
      - name: notify-tech-lead
        uses: zheng-jj/project-card-moved-notification-action@DevOpsV6
