name: Notify QA lead for testing
# Control
on:
  # Trigger
  pull_request_review:
     types: [submitted]

permissions:
  pull-requests: write
  
jobs:
  notify-QA-lead:
    runs-on: ubuntu-latest
    steps:
        # ping QA Lead for testing when code review is approved
        - name: ping QA Lead for testing
          if: ${{ github.event.review.state == 'approved' }}
          uses: thollander/actions-comment-pull-request@v1
          with:
            message: '@rlry72 User story in this pull request is ready for testing'
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        # Send notification to group discord to notify QA lead for testing
        - name: Discord notification
          if: ${{ github.event.review.state == 'approved' }}
          env:
            DISCORD_WEBHOOK: https://discord.com/api/webhooks/918820417467199498/9bnSpC3afr6euVolvsCDuNXwM6hUcElqeN5Vl2LDUObNbXEEhWiYV1tlddCHURgHBphV
          uses: Ilshidur/action-discord@master
          with:
            args: 'QA Lead, user story in pull request ${{ github.event.pull_request.html_url }} is ready to be reviewed and tested.'
