# Workflow for approving pull requests

name: Approve_Pull_Requests
description: Label relevant project board cards "Dev Team Approved" on the project board once tech lead approves code review

# Control
on:
  # Trigger
  pull_request_review:
     types: [submitted]

permissions:
  pull-requests: write

jobs:
  # label pull request as "Dev Team Approved"
  label_pr:
    # type of runner that the job will run on
      runs-on: ubuntu-latest
      
      # Task to run
      steps:
        # labelling pull-request with 'Dev Team Approved' once tech lead approves of code review.
        - name: Add label to pull request
          if: ${{ github.event.PullRequestReviewCommentEvent.action == 'APPROVED' }}
          
        # labelling issue with 'Dev Team Approved' once tech lead approves of code review.
          uses: dessant/label-actions@v2.2.0
          with:
            label: 'Dev Team Approved'

        - name: Remove label to pull request
          if: ${{ github.event.PullRequestReviewCommentEvent.action != 'APPROVED' }}
          
        # labelling issue with 'Dev Team Approved' once tech lead approves of code review.
          uses: dessant/label-actions@v2.2.0
          with:
            unlabel: 'Dev Team Approved'
              

    