name: CI for pull requests - label PR size

on: 
  [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    # label size of the pull request in the pull request
    - name: Label the PR Size
      uses: coverwallet/pr-labeler@v1.2.1
      with:
        xs_max_size: '10'
        s_max_size: '100'
        m_max_size: '500'
        l_max_size: '1000'
        exclude_files: '.txt'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
