# workflow for QA tests

# run again after merge pull request into main just in case merge has error
name: CI for push into main branch

# Controls when the workflow will run
on:
# Workflow will run when pushed to any branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov classes mocker pytest-mock pytest-html pytest-md
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with: 
        repository: zengzihui/DevOps_Oct2021_Team04
    - name: Checkout Test Script
      uses: actions/checkout@v2
      with:
        repository: rlry72/DevOpsQA_Team4
        path: tests
        token: ${{ secrets.QA_REPO }}
    - name: Linter Check with Flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Begin Pytest
      run: |
        pytest --cov -v --junitxml=reportTestScript.xml --html=report.html
        
    - name: Send mail
      if: ${{success()}}
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Optional (recommended): mail server username:
        #CHANGE TO SECRETS ASAP ${{secrets.MAIL_USERNAME}} RMB
        username: pitrecapstone
        # Optional (recommended) mail server password:
        #CHANGE to SECRETS ASAP ${{secrets.MAIL_PASSWORD}}
        password: pitrecapstone
        # Required mail subject:
        subject: Test Scripts have Finished Running (Push to main)
        # Required recipients' addresses:
        to: s10195746@connect.np.edu.sg,s10195732@connect.np.edu.sg
        # Required sender full name (address can be skipped):
        from: Github Actions # <user@example.com>
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional plain body:
        body: Test Scripts for ${{github.repository}} have finished running! (Push to main) All Test Scripts Successful!
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional attachments:
        attachments: report.html
        
    - name: Send mail
      if: ${{failure()}}
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Optional (recommended): mail server username:
        #CHANGE TO SECRETS ASAP ${{secrets.MAIL_USERNAME}} RMB
        username: pitrecapstone
        # Optional (recommended) mail server password:
        #CHANGE to SECRETS ASAP ${{secrets.MAIL_PASSWORD}}
        password: pitrecapstone
        # Required mail subject:
        subject: Test Scripts have Finished Running (Push to main)
        # Required recipients' addresses:
        to: s10195746@connect.np.edu.sg,s10195732@connect.np.edu.sg
        # Required sender full name (address can be skipped):
        from: Github Actions # <user@example.com>
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional plain body:
        body: Test Scripts for ${{github.repository}} have finished running! (Push to main) Some Test Scripts Have Failed!
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional attachments:
        attachments: report.html
          
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()    # run this step even if previous step failed
      with:
        name: Test Scripts            # Name of the check run which will be created
        path: reportTestScript.xml    # Path to test results
        reporter: java-junit        # Format of test results

    - if: ${{success()}}
      name: Discord notification
      env:
        DISCORD_WEBHOOK: https://discord.com/api/webhooks/918820417467199498/9bnSpC3afr6euVolvsCDuNXwM6hUcElqeN5Vl2LDUObNbXEEhWiYV1tlddCHURgHBphV
      uses: Ilshidur/action-discord@master
      with:
        args: 'Test Scripts for {{ EVENT_PAYLOAD.repository.full_name }} (Push to main) successfully passed.'
        
    - if: ${{failure()}}
      name: Discord notification
      env:
        DISCORD_WEBHOOK: https://discord.com/api/webhooks/918820417467199498/9bnSpC3afr6euVolvsCDuNXwM6hUcElqeN5Vl2LDUObNbXEEhWiYV1tlddCHURgHBphV
      uses: Ilshidur/action-discord@master
      with:
        args: 'Test Scripts for {{ EVENT_PAYLOAD.repository.full_name }} (Push to main) have failed.'
    
    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v3
      id: ciff
      if: ${{failure()}}
      with:
        title: Failed Test Scripts
        content-filepath: report.md
        labels: |
          Failed Test Script
          automated issue
        assignees:
          JianOon 

    - name: Notify Tech Lead on Issue In-Review
      uses: peter-evans/create-or-update-comment@v1.4.5
      if: ${{failure()}}
      with:
        issue-number: ${{ steps.ciff.outputs.issue-number }}
        body: |
          @JianOon Please review with @rlry72