# workflow for QA tests

name: CI for push in all branches

# Controls when the workflow will run
on:
# Workflow will run when pushed to any branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with: 
        repository: zengzihui/DevOps_Oct2021_Team04
    - name: Checkout Test Script
      uses: actions/checkout@v2
      with:
        repository: rlry72/DevOpsQA_Team4
        path: tests
        token: ${{ secrets.QA_REPO }}
    - name: Linter Check with Flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Begin Pytest
      run: |
        pytest --cov -v --junitxml=reportTestScript.xml
    - name: Publish Test Script Results
      uses: EnricoMi/publish-unit-test-result-action@v1.24
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: reportTestScript.xml
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Optional (recommended): mail server username:
        #CHANGE TO SECRETS ASAP ${{secrets.MAIL_USERNAME}}
        username: pitrecapstone@gmail.com
        # Optional (recommended) mail server password:
        #CHANGE to SECRETS ASAP ${{secrets.MAIL_PASSWORD}}
        password: pitrecapstone
        # Required mail subject:
        subject: Test Scripts has Finished Running
        # Required recipients' addresses:
        to: s10195746@connect.np.edu.sg,s10195732@connect.np.edu.sg
        # Required sender full name (address can be skipped):
        from: Github Actions # <user@example.com>
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional plain body:
        body: Test Scripts of ${{github.repository}} has finished running!
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional attachments:

        
    
